### ISSUE TITLE
Beta: Font size too big on some devices

### ISSUE THREAD

**Issue by tamslinn** [emoncms/AndroidApp#46]
See https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/81

**Comment by tamslinn** [comment]
@glynhudson I've merged a change which reverts the font size on phones, and increases it on tablets. I've tested with emulator and seems to work, can you try it out? Thanks.

**Comment by glynhudson** [comment]
This is how it looks for me: https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/86?u=glyn.hudson

It looks good, however there does not seem to be a large difference between phone and tablet. However, as I mentioned in the forum post I could never recreate the large overflow text issue. I quite like the large Power Now value. 

I'll keep this issue open until we hear back from the forum.

**Comment by joyrider3774** [comment]
overlap problem is fixed on my phone (huawei ascend p7) with new version. My phone's screen resolution is set at 720*1280 perhaps your's is bigger and thus not having the problem. You can check your screen resolution in "settings/about my phone" on android well at least on my 5.1 android version. I have no idea what my dpi is set at though or if android even uses that / works similar as it does on windows. At work we used to have similar problems in win32 programs we create. But i just don't know enough about android to see if that's the case. Looking at your screenshot of your phone i did notice you have much more spacing between the 2 numbers being shown that (used to) overlap. perhaps it's due to resolution of your phone being higher. Also i do notice something else as i already mentioned before on the forums switching accounts seems to have some kind of impact. I added 2 accounts and both work if i switch accounts i can see the font size being bigger (displaying all zero's for the values) for a split second and then revert to the smaller font. Maybe this was somehow interfering during the change was made. 

Secondly the font size setting under display has an effect on the spacing between the font's and thus font size inside the emoncms app. If i change the text size from normal to extra big they will overlap again and they definatly do while siwtching accounts. If you want i can create a new youtube video about this showing it. 

I'll create the video as i can easily show it now. try adding a new account and don't add a page. The page shows all 0 values initially but if you compare font sizes to an account that is working you'll notice the font size is bigger. This is what i said i see if i switch accounts (if both have pages and work) for split second but now you can keep this view forever untill you add a page then font size changes again.

Oh i noticed something it says 0.00KWH and then KWH in small text like it should in that case:

edit: here's the video:
- shows effect of text size on emoncms (will overlapp again with high numbers on my phone)
- shows force close when adding a second account after i deleted that second account and had at least one other account (only noticed this during recording now)
- shows the 0.00KW text while it should be 0.00 as the kwh is written in smaller text besides it so it's displayed twice now(this is what shows during switching of accounts for a split second (until data is available, not shown in video or i did not explicitly show this)

https://www.youtube.com/watch?v=jzo0GCNBCfo

**Comment by glynhudson** [comment]
Hi @joyrider3774 thanks for helping to debug this. It's good to hear that the original problem of the overflow text issue has been fixed. I will close this issue. The font size changing with Android textsize is expected. 

Let's continue the discussion on the forum or create a new issue for any further specific issues to address.
